// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddtoCartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addtoCart() {
    driver.get("https://www.bestbuy.ca/en-ca");
    driver.manage().window().setSize(new Dimension(1382, 886));
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("search")).sendKeys("gaming mouse");
    driver.findElement(By.name("search")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(4) .x-crumb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,207)");
    driver.findElement(By.cssSelector(".col-xs-4_1EA1G:nth-child(2) .sliderTarget_2Q87g")).click();
    driver.findElement(By.cssSelector(".col-xs-12_198le:nth-child(1) .sliderTarget_2Q87g:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,73)");
    driver.findElement(By.cssSelector(".addToCartButton_1op0t")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".basketIcon_1lhg2")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) .quantityStepperButton_a-yJ7:nth-child(3) path")).click();
  }
}
