// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HighLowTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void highLow() {
    driver.get("https://www.bestbuy.ca/en-ca");
    driver.manage().window().setSize(new Dimension(1382, 886));
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("search")).sendKeys("monitors");
    driver.findElement(By.name("search")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,272)");
    driver.findElement(By.cssSelector(".primaryCta_oTAT9 > .content_3Dbgg")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,347)");
    js.executeScript("window.scrollTo(0,771)");
    driver.findElement(By.id("Sort")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Sort"));
      dropdown.findElement(By.xpath("//option[. = 'Price High-Low']")).click();
    }
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,245)");
    js.executeScript("window.scrollTo(0,767)");
    driver.close();
  }
}
